In [1]:
import math
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("../data/whoop_fitness_dataset_100k.csv")

In [2]:
# Get the number of rows and columns

df.shape

(100000, 39)

In [3]:
# Get the number of not missing values for each features
# Get the number of data types in the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 39 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   user_id                  100000 non-null  str
 1   date                     100000 non-null  str
 2   day_of_week              100000 non-null  str
 3   age                      100000 non-null  int64
 4   gender                   100000 non-null  str
 5   weight_kg                100000 non-null  float64
 6   height_cm                100000 non-null  float64
 7   fitness_level            100000 non-null  str
 8   primary_sport            100000 non-null  str
 9   recovery_score           100000 non-null  float64
 10  day_strain               100000 non-null  float64
 11  sleep_hours              100000 non-null  float64
 12  sleep_efficiency         100000 non-null  float64
 13  sleep_performance        100000 non-null  float64
 14  light_sleep_hours        100000 non-null  float64
 15  rem_sleep_hours          100000 non-null  float64
 16  deep_sleep_hours         100000 non-null  float64
 17  wake_ups                 100000 non-null  int64
 18  time_to_fall_asleep_min  100000 non-null  float64
 19  hrv                      100000 non-null  float64
 20  resting_heart_rate       100000 non-null  float64
 21  hrv_baseline             100000 non-null  int64
 22  rhr_baseline             100000 non-null  int64
 23  respiratory_rate         100000 non-null  float64
 24  skin_temp_deviation      100000 non-null  float64
 25  calories_burned          100000 non-null  float64
 26  workout_completed        100000 non-null  int64
 27  activity_type            100000 non-null  str
 28  activity_duration_min    100000 non-null  int64
 29  activity_strain          100000 non-null  float64
 30  avg_heart_rate           100000 non-null  float64
 31  max_heart_rate           100000 non-null  float64
 32  activity_calories        100000 non-null  float64
 33  hr_zone_1_min            100000 non-null  float64
 34  hr_zone_2_min            100000 non-null  float64
 35  hr_zone_3_min            100000 non-null  float64
 36  hr_zone_4_min            100000 non-null  float64
 37  hr_zone_5_min            100000 non-null  float64
 38  workout_time_of_day      54010 non-null   str
dtypes: float64(25), int64(6), str(8)
memory usage: 29.8 MB

In [4]:
# Get the summary statistics of the dataset (numerical features)

df.describe(include=["number"]).T

,count,mean,std,min,25%,50%,75%,max
age,100000.0,41.642950,13.257307,18.00,30.00,41.00,53.00,64.00
weight_kg,100000.0,72.707693,13.896367,38.10,62.90,72.10,82.00,115.00
height_cm,100000.0,171.754403,9.337338,149.40,165.30,171.50,178.90,195.80
recovery_score,100000.0,65.130442,17.698584,5.00,52.40,64.50,77.40,100.00
day_strain,100000.0,9.911999,4.489623,0.00,6.65,9.53,12.89,21.00
sleep_hours,100000.0,7.296272,0.972416,4.00,6.65,7.46,8.03,10.00
sleep_efficiency,100000.0,82.883422,10.222554,50.00,76.50,85.00,90.50,100.00
sleep_performance,100000.0,100.000000,0.000000,100.00,100.00,100.00,100.00,100.00
light_sleep_hours,100000.0,4.378101,0.603068,2.24,3.98,4.46,4.82,6.21
rem_sleep_hours,100000.0,1.641338,0.242734,0.81,1.48,1.66,1.82,2.43
deep_sleep_hours,100000.0,1.276817,0.200364,0.60,1.14,1.28,1.42,1.93
wake_ups,100000.0,0.338920,0.618803,0.00,0.00,0.00,1.00,7.00
time_to_fall_asleep_min,100000.0,5.577995,2.183646,5.00,5.00,5.00,5.00,51.30
hrv,100000.0,73.235746,28.477633,20.00,51.50,72.60,94.50,150.00
resting_heart_rate,100000.0,57.627420,9.268706,40.00,50.30,57.10,64.80,85.50
hrv_baseline,100000.0,73.356860,25.040026,30.00,54.00,73.00,93.00,119.00
rhr_baseline,100000.0,59.163250,8.392176,45.00,52.00,59.00,66.00,74.00
respiratory_rate,100000.0,15.993832,2.002110,7.50,14.60,16.00,17.30,24.50
skin_temp_deviation,100000.0,0.003286,0.500186,-2.39,-0.34,0.01,0.34,2.02
calories_burned,100000.0,3286.646650,702.036628,871.00,2784.00,3236.00,3754.00,5695.00
workout_completed,100000.0,0.540100,0.498392,0.00,0.00,1.00,1.00,1.00
activity_duration_min,100000.0,27.646820,29.018375,0.00,0.00,27.00,51.00,119.00
activity_strain,100000.0,5.740622,6.442949,0.00,0.00,2.83,11.98,21.00
avg_heart_rate,100000.0,74.555414,69.630320,0.00,0.00,115.90,138.40,181.80
max_heart_rate,100000.0,84.158187,78.495935,0.00,0.00,132.40,156.20,202.00
activity_calories,100000.0,241.158940,299.910276,0.00,0.00,84.00,455.00,1831.00
hr_zone_1_min,100000.0,4.492818,6.081894,0.00,0.00,1.40,7.30,45.50
hr_zone_2_min,100000.0,6.772501,7.527003,0.00,0.00,5.00,12.40,46.50
hr_zone_3_min,100000.0,7.270141,8.371101,0.00,0.00,5.00,13.60,42.90
hr_zone_4_min,100000.0,6.550316,8.492293,0.00,0.00,1.20,12.40,46.60
hr_zone_5_min,100000.0,2.607983,3.829844,0.00,0.00,0.00,4.60,29.50

In [5]:
# Get the statistics of the dataset (Categorical features)

df.describe(include=["object", "str"]).T

                      count unique           top   freq
user_id              100000    286    USER_00026    399
date                 100000    399    2023-01-01    286
day_of_week          100000      7        Sunday  14419
gender               100000      2          Male  55734
fitness_level        100000      4  Intermediate  40702
primary_sport        100000      8       Running  13961
activity_type        100000      9      Rest Day  45990
workout_time_of_day   54010      3       Morning  21505

In [6]:
# Get the number of missing values of each features

df.isnull().sum()

user_id                        0
date                           0
day_of_week                    0
age                            0
gender                         0
weight_kg                      0
height_cm                      0
fitness_level                  0
primary_sport                  0
recovery_score                 0
day_strain                     0
sleep_hours                    0
sleep_efficiency               0
sleep_performance              0
light_sleep_hours              0
rem_sleep_hours                0
deep_sleep_hours               0
wake_ups                       0
time_to_fall_asleep_min        0
hrv                            0
resting_heart_rate             0
hrv_baseline                   0
rhr_baseline                   0
respiratory_rate               0
skin_temp_deviation            0
calories_burned                0
workout_completed              0
activity_type                  0
activity_duration_min          0
activity_strain                0
avg_heart_rate                 0
max_heart_rate                 0
activity_calories              0
hr_zone_1_min                  0
hr_zone_2_min                  0
hr_zone_3_min                  0
hr_zone_4_min                  0
hr_zone_5_min                  0
workout_time_of_day        45990
dtype: int64

In [7]:
# Get the number of duplicated rows

df.duplicated().sum()

np.int64(0)

In [8]:
# Get the count of each unique values of each features
# for checking garbage values

for i in df.select_dtypes(include=["str", "object"]).columns:
    print(df[i].value_counts())
    print("***"*10)

user_id
USER_00026    399
USER_00032    399
USER_00119    399
USER_00200    399
USER_00048    398
             ...
USER_00101    302
USER_00229    302
USER_00155    300
USER_00223    300
USER_00286    137
Name: count, Length: 286, dtype: int64
******************************
date
2023-01-01    286
2023-01-02    286
2023-01-03    286
2023-01-04    286
2023-01-05    286
             ...
2024-01-30     17
2024-01-31     16
2024-02-01     11
2024-02-02      6
2024-02-03      4
Name: count, Length: 399, dtype: int64
******************************
day_of_week
Sunday       14419
Monday       14378
Tuesday      14320
Wednesday    14282
Thursday     14232
Friday       14201
Saturday     14168
Name: count, dtype: int64
******************************
gender
Male      55734
Female    44266
Name: count, dtype: int64
******************************
fitness_level
Intermediate    40702
Advanced        27447
Beginner        19065
Elite           12786
Name: count, dtype: int64
******************************
primary_sport
Running            13961
HIIT               13826
Yoga               12683
Swimming           12570
Weight Training    12373
Walking            11644
CrossFit           11576
Cycling            11367
Name: count, dtype: int64
******************************
activity_type
Rest Day           45990
HIIT                7254
Running             7252
Yoga                6919
Weight Training     6859
CrossFit            6609
Swimming            6578
Walking             6385
Cycling             6154
Name: count, dtype: int64
******************************
workout_time_of_day
Morning      21505
Afternoon    16258
Evening      16247
Name: count, dtype: int64
******************************

In [9]:
# Get all the unique values of each features
# for checking inconsistent values

columns = df.select_dtypes(include=["object", "str"])

for col in columns:
    print(f"============ feature {col} ============")
    print(df[col].unique())

============ feature user_id ============
<StringArray>
['USER_00001', 'USER_00002', 'USER_00003', 'USER_00004', 'USER_00005',
 'USER_00006', 'USER_00007', 'USER_00008', 'USER_00009', 'USER_00010',
 ...
 'USER_00277', 'USER_00278', 'USER_00279', 'USER_00280', 'USER_00281',
 'USER_00282', 'USER_00283', 'USER_00284', 'USER_00285', 'USER_00286']
Length: 286, dtype: str
============ feature date ============
<StringArray>
['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
 '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10',
 ...
 '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28', '2024-01-29',
 '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03']
Length: 399, dtype: str
============ feature day_of_week ============
<StringArray>
['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
Length: 7, dtype: str
============ feature gender ============
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
============ feature fitness_level ============
<StringArray>
['Beginner', 'Elite', 'Intermediate', 'Advanced']
Length: 4, dtype: str
============ feature primary_sport ============
<StringArray>
['Weight Training',        'CrossFit',         'Cycling',        'Swimming',
         'Walking',            'Yoga',         'Running',            'HIIT']
Length: 8, dtype: str
============ feature activity_type ============
<StringArray>
[       'Rest Day', 'Weight Training',         'Running',            'Yoga',
        'CrossFit',         'Cycling',         'Walking',            'HIIT',
        'Swimming']
Length: 9, dtype: str
============ feature workout_time_of_day ============
<StringArray>
[nan, 'Evening', 'Morning', 'Afternoon']
Length: 4, dtype: str

In [10]:
# Unique Values of each features

print("********************** CATEGORICAL FEATURES **********************")
for col in df.select_dtypes(include=["object", "str"]).columns:
    print(df[col].value_counts())
    print(f"total unique values: {len(df[col].dropna().unique())}")
    print("=====================================\n")

print("********************** NUMERICAL FEATURES **********************")
for col in df.select_dtypes(include=["number"]).columns:
    print(df[col].value_counts())
    print(f"total unique values: {len(df[col].dropna().unique())}")
    print(f"max value: {df[col].max()}")
    print(f"min value: {df[col].min()}")
    print("=====================================\n")

********************** CATEGORICAL FEATURES **********************
user_id
USER_00026    399
USER_00032    399
USER_00119    399
USER_00200    399
USER_00048    398
             ...
USER_00101    302
USER_00229    302
USER_00155    300
USER_00223    300
USER_00286    137
Name: count, Length: 286, dtype: int64
total unique values: 286
=====================================

date
2023-01-01    286
2023-01-02    286
2023-01-03    286
2023-01-04    286
2023-01-05    286
             ...
2024-01-30     17
2024-01-31     16
2024-02-01     11
2024-02-02      6
2024-02-03      4
Name: count, Length: 399, dtype: int64
total unique values: 399
=====================================

day_of_week
Sunday       14419
Monday       14378
Tuesday      14320
Wednesday    14282
Thursday     14232
Friday       14201
Saturday     14168
Name: count, dtype: int64
total unique values: 7
=====================================

gender
Male      55734
Female    44266
Name: count, dtype: int64
total unique values: 2
=====================================

fitness_level
Intermediate    40702
Advanced        27447
Beginner        19065
Elite           12786
Name: count, dtype: int64
total unique values: 4
=====================================

primary_sport
Running            13961
HIIT               13826
Yoga               12683
Swimming           12570
Weight Training    12373
Walking            11644
CrossFit           11576
Cycling            11367
Name: count, dtype: int64
total unique values: 8
=====================================

activity_type
Rest Day           45990
HIIT                7254
Running             7252
Yoga                6919
Weight Training     6859
CrossFit            6609
Swimming            6578
Walking             6385
Cycling             6154
Name: count, dtype: int64
total unique values: 9
=====================================

workout_time_of_day
Morning      21505
Afternoon    16258
Evening      16247
Name: count, dtype: int64
total unique values: 3
=====================================

********************** NUMERICAL FEATURES **********************
age
50    3952
38    3831
31    3509
51    3347
28    3264
60    3113
37    2977
29    2971
45    2971
58    2954
56    2805
40    2576
44    2569
24    2531
41    2469
25    2446
54    2370
20    2346
63    2211
23    2198
53    2149
27    2149
26    2137
61    2128
64    2115
59    2085
47    2046
55    2035
48    2035
21    1993
35    1840
30    1779
57    1752
32    1747
33    1657
19    1404
42    1385
43    1346
52    1338
46    1267
39    1088
62    1083
34    1066
36     960
18     693
22     673
49     640
Name: count, dtype: int64
total unique values: 47
max value: 64
min value: 18
=====================================

weight_kg
77.7    1380
79.4    1101
72.4    1061
75.0    1060
68.6    1052
        ...
61.6     303
86.9     303
81.4     303
69.7     300
76.2     300
Name: count, Length: 224, dtype: int64
total unique values: 224
max value: 115.0
min value: 38.1
=====================================

height_cm
181.0    1760
169.8    1390
174.1    1377
169.0    1120
164.5    1114
         ...
190.0     305
158.4     304
182.1     303
172.1     303
153.9     137
Name: count, Length: 188, dtype: int64
total unique values: 188
max value: 195.8
min value: 149.4
=====================================

recovery_score
100.0    4123
62.9      240
58.1      238
61.2      237
61.1      235
         ...
14.3        1
13.3        1
17.9        1
7.2         1
14.0        1
Name: count, Length: 879, dtype: int64
total unique values: 879
max value: 100.0
min value: 5.0
=====================================

day_strain
21.00    1362
0.00      620
7.37      113
7.58      111
7.79      110
         ...
0.08        1
0.47        1
0.17        1
0.20        1
0.09        1
Name: count, Length: 2101, dtype: int64
total unique values: 2101
max value: 21.0
min value: 0.0
=====================================

sleep_hours
8.04    493
7.72    493
7.78    483
7.91    479
7.89    479
       ...
9.53      1
9.51      1
9.77      1
9.72      1
9.91      1
Name: count, Length: 583, dtype: int64
total unique values: 583
max value: 10.0
min value: 4.0
=====================================

sleep_efficiency
100.0    1296
88.7      506
89.8      502
87.4      499
90.1      495
         ...
50.9        8
52.1        7
51.4        7
50.2        6
51.0        3
Name: count, Length: 501, dtype: int64
total unique values: 501
max value: 100.0
min value: 50.0
=====================================

sleep_performance
100.0    100000
Name: count, dtype: int64
total unique values: 1
max value: 100.0
min value: 100.0
=====================================

light_sleep_hours
4.67    748
4.77    744
4.58    737
4.64    733
4.65    729
       ...
6.10      1
6.00      1
2.25      1
2.33      1
6.19      1
Name: count, Length: 383, dtype: int64
total unique values: 383
max value: 6.21
min value: 2.24
=====================================

rem_sleep_hours
1.72    1700
1.70    1671
1.69    1664
1.63    1647
1.66    1638
        ...
2.34       3
2.35       1
2.43       1
2.36       1
2.41       1
Name: count, Length: 160, dtype: int64
total unique values: 160
max value: 2.43
min value: 0.81
=====================================

deep_sleep_hours
1.30    2036
1.31    2018
1.26    1998
1.27    1993
1.23    1963
        ...
1.90       1
1.89       1
1.92       1
1.86       1
1.93       1
Name: count, Length: 133, dtype: int64
total unique values: 133
max value: 1.93
min value: 0.6
=====================================

wake_ups
0    72762
1    21687
2     4613
3      791
4      131
5       15
7        1
Name: count, dtype: int64
total unique values: 7
max value: 7
min value: 0
=====================================

time_to_fall_asleep_min
5.0     85506
5.1       412
5.5       408
5.2       401
5.4       375
        ...
33.1        1
33.8        1
35.4        1
51.3        1
46.8        1
Name: count, Length: 289, dtype: int64
total unique values: 289
max value: 51.3
min value: 5.0
=====================================

hrv
20.0     2534
62.6      156
62.5      149
79.7      146
66.0      144
         ...
149.5       1
144.5       1
146.2       1
146.7       1
148.9       1
Name: count, Length: 1296, dtype: int64
total unique values: 1296
max value: 150.0
min value: 20.0
=====================================

resting_heart_rate
40.0    1623
50.8     416
50.4     415
51.4     413
51.9     408
        ...
85.5       1
85.4       1
83.8       1
85.2       1
83.5       1
Name: count, Length: 447, dtype: int64
total unique values: 447
max value: 85.5
min value: 40.0
=====================================

hrv_baseline
64     3667
73     2789
75     2490
38     2465
65     2406
       ...
85      332
118     326
67      310
59      308
98      304
Name: count, Length: 86, dtype: int64
total unique values: 86
max value: 119
min value: 30
=====================================

rhr_baseline
55    6146
52    6094
49    5946
53    5473
63    5168
72    5074
57    4657
45    4177
62    3782
74    3781
56    3579
61    3375
60    3344
65    3249
66    3080
67    2894
51    2781
50    2718
73    2542
59    2526
68    2490
64    2460
70    2174
58    2172
71    2119
69    2056
46    1873
48    1683
47    1446
54    1141
Name: count, dtype: int64
total unique values: 30
max value: 74
min value: 45
=====================================

respiratory_rate
15.9    2058
16.2    2030
15.5    2002
16.1    1985
15.8    1967
        ...
23.4       1
7.5        1
23.8       1
24.3       1
8.8        1
Name: count, Length: 157, dtype: int64
total unique values: 157
max value: 24.5
min value: 7.5
=====================================

skin_temp_deviation
 0.02    836
-0.03    835
 0.04    820
-0.06    806
 0.23    805
        ...
-2.21      1
 2.02      1
 1.73      1
 1.85      1
 1.72      1
Name: count, Length: 376, dtype: int64
total unique values: 376
max value: 2.02
min value: -2.39
=====================================

calories_burned
3016.0    77
3144.0    75
3433.0    75
3156.0    74
3125.0    73
          ..
5330.0     1
5586.0     1
1535.0     1
1480.0     1
5327.0     1
Name: count, Length: 3831, dtype: int64
total unique values: 3831
max value: 5695.0
min value: 871.0
=====================================

workout_completed
1    54010
0    45990
Name: count, dtype: int64
total unique values: 2
max value: 1
min value: 0
=====================================

activity_duration_min
0      45990
45      1472
47      1328
51      1321
46      1304
       ...
106       61
114       56
108       55
112       55
118       48
Name: count, Length: 103, dtype: int64
total unique values: 103
max value: 119
min value: 0
=====================================

activity_strain
0.00     45995
21.00      122
12.59       65
13.36       62
14.78       62
         ...
20.63        1
19.92        1
0.16         1
20.98        1
0.65         1
Name: count, Length: 2058, dtype: int64
total unique values: 2058
max value: 21.0
min value: 0.0
=====================================

avg_heart_rate
0.0      45990
134.2      180
135.2      177
134.0      174
133.5      174
         ...
174.8        1
177.8        1
174.3        1
178.6        1
178.1        1
Name: count, Length: 769, dtype: int64
total unique values: 769
max value: 181.8
min value: 0.0
=====================================

max_heart_rate
0.0      45990
153.2      164
150.0      161
151.9      160
154.7      160
         ...
195.8        1
197.9        1
194.1        1
196.8        1
195.7        1
Name: count, Length: 806, dtype: int64
total unique values: 806
max value: 202.0
min value: 0.0
=====================================

activity_calories
0.0       45995
108.0       125
96.0        117
86.0        114
110.0       113
          ...
1622.0        1
1438.0        1
1290.0        1
1375.0        1
1309.0        1
Name: count, Length: 1448, dtype: int64
total unique values: 1448
max value: 1831.0
min value: 0.0
=====================================

hr_zone_1_min
0.0     46109
3.5       565
4.0       548
4.2       546
2.9       544
        ...
28.3        1
27.3        1
29.0        1
40.3        1
26.6        1
Name: count, Length: 302, dtype: int64
total unique values: 302
max value: 45.5
min value: 0.0
=====================================

hr_zone_2_min
0.0     45990
10.2      407
10.3      405
11.4      400
8.8       399
        ...
45.8        1
35.3        1
35.6        1
36.4        1
39.5        1
Name: count, Length: 378, dtype: int64
total unique values: 378
max value: 46.5
min value: 0.0
=====================================

hr_zone_3_min
0.0     45990
5.8       373
6.0       361
5.6       358
5.9       355
        ...
40.3        1
38.8        1
41.2        1
41.7        1
39.5        1
Name: count, Length: 394, dtype: int64
total unique values: 394
max value: 42.9
min value: 0.0
=====================================

hr_zone_4_min
0.0     46133
1.6       369
1.9       365
1.5       363
1.2       362
        ...
42.1        1
38.9        1
43.6        1
46.3        1
42.5        1
Name: count, Length: 435, dtype: int64
total unique values: 435
max value: 46.6
min value: 0.0
=====================================

hr_zone_5_min
0.0     52270
4.0       628
4.3       624
3.9       593
3.8       591
        ...
26.7        1
25.5        1
27.3        1
28.0        1
25.4        1
Name: count, Length: 261, dtype: int64
total unique values: 261
max value: 29.5
min value: 0.0
=====================================