In [1]:
from sklearn.metrics import (

    root_mean_squared_error, 
    mean_squared_error, 
    mean_absolute_error,
    mean_absolute_percentage_error,
    max_error,
    r2_score
)
import pandas as pd
import numpy as np

y_test = pd.read_csv("../data/y_test.csv")
predict_dtr = pd.read_csv("../data/predict_dtr.csv")
predict_hgbr = pd.read_csv("../data/predict_hgbr.csv")
predict_xgbr = pd.read_csv("../data/predict_xgbr.csv")
predict_lgbm = pd.read_csv("../data/predict_lgbm.csv")

models = {
    "Decision Tree Regressor": predict_dtr,
    "HistGradient Boosting Regressor": predict_hgbr,
    "XGBoost Regressor": predict_xgbr,
    "LGBM Regressor": predict_lgbm
}

evaluation_results = []

for model_name, prediction in models.items():
    rmse = root_mean_squared_error(y_test, prediction)
    mse = mean_squared_error(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)
    me = max_error(y_test, prediction)
    r2 = r2_score(y_test, prediction)
    
    evaluation_results.append([
        model_name,
        rmse,
        mse,
        mae,
        mape,
        me,
        r2
    ])
    
evaluation_table = pd.DataFrame(
    evaluation_results,
    columns=[
        "Model",
        "RMSE",
        "MSE",
        "MAE",
        "MAPE",
        "Max Error",
        "R² Score"
    ]
)

evaluation_table

,Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Decision Tree Regressor,19.058841,363.239412,15.108899,0.258951,74.000000,-0.233219
1,HistGradient Boosting Regressor,12.905595,166.554388,10.368203,0.183269,48.978922,0.434538
2,XGBoost Regressor,13.264736,175.953229,10.616530,0.186817,49.252805,0.402628
3,LGBM Regressor,12.844471,164.980446,10.306059,0.182767,49.253524,0.439882

In [2]:
import json

models = ["Decision Tree", "HistoGradient Boosting Regressor", "XGBoost Regressor", "LGBM Regressor"]
best_params = []

with open("../json/dtr_tuned_params.json", "r") as f:
    dtr_best_params = json.load(f)
    best_params.append(dtr_best_params)
    
with open("../json/hgbr_tuned_params.json", "r") as f:
    hgbr_best_params = json.load(f)
    best_params.append(hgbr_best_params)
    
with open("../json/xgbr_tuned_params.json", "r") as f:
    xgbr_best_params = json.load(f)
    best_params.append(xgbr_best_params)
    
with open("../json/lgbm_tuned_params.json", "r") as f:
    lgbm_best_params = json.load(f)
    best_params.append(lgbm_best_params)
    
for i, param in enumerate(best_params):
    print(f"{models[i]} best hyperparameters:")
    print(f"{json.dumps(param, indent=4)}\n")

Decision Tree best hyperparameters:
{
    "max_depth": 9,
    "min_samples_leaf": 19,
    "min_samples_split": 5
}

HistoGradient Boosting Regressor best hyperparameters:
{
    "l2_regularization": 0.4234014807063696,
    "learning_rate": 0.08502748845335824,
    "max_iter": 235,
    "max_leaf_nodes": 38,
    "min_samples_leaf": 20
}

XGBoost Regressor best hyperparameters:
{
    "colsample_bytree": 0.8159364365206693,
    "learning_rate": 0.048581632699606185,
    "max_depth": 6,
    "n_estimators": 259,
    "subsample": 0.8796596399465607
}

LGBM Regressor best hyperparameters:
{
    "colsample_bytree": 0.6557975442608167,
    "learning_rate": 0.06842892970704363,
    "n_estimators": 114,
    "num_leaves": 58,
    "subsample": 0.8542703315240834
}

In [3]:
from sklearn.metrics import (

    root_mean_squared_error, 
    mean_squared_error, 
    mean_absolute_error,
    mean_absolute_percentage_error,
    max_error,
    r2_score
)

predict_dtr_hypertuned = pd.read_csv("../data/predict_dtr_hypertuned.csv")
predict_hgbr_hypertuned = pd.read_csv("../data/predict_hgbr_hypertuned.csv")
predict_xgbr_hypertuned = pd.read_csv("../data/predict_xgbr_hypertuned.csv")
predict_lgbm_hypertuned = pd.read_csv("../data/predict_lgbm_hypertuned.csv")

models = {
    "Decision Tree Regressor": predict_dtr_hypertuned,
    "HistGradient Boosting Regressor": predict_hgbr_hypertuned,
    "XGBoost Regressor": predict_xgbr_hypertuned,
    "LGBM Regressor": predict_lgbm_hypertuned
}

evaluation_results = []

for model_name, prediction in models.items():
    rmse = root_mean_squared_error(y_test, prediction)
    mse = mean_squared_error(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)
    me = max_error(y_test, prediction)
    r2 = r2_score(y_test, prediction)
    
    evaluation_results.append([
        model_name,
        rmse,
        mse,
        mae,
        mape,
        me,
        r2
    ])
    
evaluation_table_hypertuned = pd.DataFrame(
    evaluation_results,
    columns=[
        "Hypertuned Model",
        "RMSE",
        "MSE",
        "MAE",
        "MAPE",
        "Max Error",
        "R² Score"
    ]
)

evaluation_table_hypertuned

,Hypertuned Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Decision Tree Regressor,13.917370,193.693194,11.136680,0.195398,48.816741,0.342400
1,HistGradient Boosting Regressor,12.893326,166.237861,10.348992,0.183076,49.602389,0.435613
2,XGBoost Regressor,12.851257,165.154802,10.316265,0.182499,48.852080,0.439290
3,LGBM Regressor,12.935193,167.319206,10.400672,0.185029,50.391885,0.431941

In [4]:
display(evaluation_table)
display(evaluation_table_hypertuned)

,Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Decision Tree Regressor,19.058841,363.239412,15.108899,0.258951,74.000000,-0.233219
1,HistGradient Boosting Regressor,12.905595,166.554388,10.368203,0.183269,48.978922,0.434538
2,XGBoost Regressor,13.264736,175.953229,10.616530,0.186817,49.252805,0.402628
3,LGBM Regressor,12.844471,164.980446,10.306059,0.182767,49.253524,0.439882

,Hypertuned Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Decision Tree Regressor,13.917370,193.693194,11.136680,0.195398,48.816741,0.342400
1,HistGradient Boosting Regressor,12.893326,166.237861,10.348992,0.183076,49.602389,0.435613
2,XGBoost Regressor,12.851257,165.154802,10.316265,0.182499,48.852080,0.439290
3,LGBM Regressor,12.935193,167.319206,10.400672,0.185029,50.391885,0.431941