In [7]:
from sklearn.metrics import (

    root_mean_squared_error, 
    mean_squared_error, 
    mean_absolute_error,
    mean_absolute_percentage_error,
    max_error,
    r2_score
)
import pandas as pd
import numpy as np

y_test = pd.read_csv("../data/y_test.csv")
predict_dtr = pd.read_csv("../data/predict_dtr.csv")
predict_hgbr = pd.read_csv("../data/predict_hgbr.csv")
predict_xgbr = pd.read_csv("../data/predict_xgbr.csv")
predict_lgbm = pd.read_csv("../data/predict_lgbm.csv")

models = {
    "Decision Tree Regressor": predict_dtr,
    "HistGradient Boosting Regressor": predict_hgbr,
    "XGBoost Regressor": predict_xgbr,
    "LGBM Regressor": predict_lgbm
}

evaluation_results = []

for model_name, prediction in models.items():
    rmse = root_mean_squared_error(y_test, prediction)
    mse = mean_squared_error(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)
    me = max_error(y_test, prediction)
    r2 = r2_score(y_test, prediction)
    
    evaluation_results.append([
        model_name,
        rmse,
        mse,
        mae,
        mape,
        me,
        r2
    ])
    
evaluation_table = pd.DataFrame(
    evaluation_results,
    columns=[
        "Model",
        "RMSE",
        "MSE",
        "MAE",
        "MAPE",
        "Max Error",
        "R² Score"
    ]
)

evaluation_table.to_csv("../results/evaluation_metrics_default_models.csv", index=False)

evaluation_table

,Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Decision Tree Regressor,18.985450,360.447327,15.056840,0.258338,80.600000,-0.223740
1,HistGradient Boosting Regressor,13.106623,171.783572,10.532501,0.187643,49.529573,0.416785
2,XGBoost Regressor,13.391723,179.338233,10.745075,0.190307,49.483235,0.391136
3,LGBM Regressor,13.036671,169.954801,10.480336,0.186468,49.032011,0.422993

In [8]:

predict_lgbm_bayesian = pd.read_csv("../data/predict_lgbm_bayesian.csv")
predict_lgbm_successive_halving = pd.read_csv("../data/predict_lgbm_successive_halving.csv")
predict_lgbm_cmaes = pd.read_csv("../data/predict_lgbm_cmaes.csv")

models = {
    "Default LGBM Regressor": predict_lgbm,
    "LGBM Regressor with Bayesian Optimization": predict_lgbm_bayesian,
    "LGBM Regressor with Successive Halving": predict_lgbm_successive_halving,
    "LGBM Regressor CMA-ES": predict_lgbm_cmaes
}

evaluation_results = []

for model_name, prediction in models.items():
    rmse = root_mean_squared_error(y_test, prediction)
    mse = mean_squared_error(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    mape = mean_absolute_percentage_error(y_test, prediction)
    me = max_error(y_test, prediction)
    r2 = r2_score(y_test, prediction)
    
    evaluation_results.append([
        model_name,
        rmse,
        mse,
        mae,
        mape,
        me,
        r2
    ])
    
evaluation_table = pd.DataFrame(
    evaluation_results,
    columns=[
        "Model",
        "RMSE",
        "MSE",
        "MAE",
        "MAPE",
        "Max Error",
        "R² Score"
    ]
)

evaluation_table.to_csv("../results/evaluation_metrics_LGBM_hyperparameter_tuning.csv", index=False)

evaluation_table

,Model,RMSE,MSE,MAE,MAPE,Max Error,R² Score
0,Default LGBM Regressor,13.036671,169.954801,10.480336,0.186468,49.032011,0.422993
1,LGBM Regressor with Bayesian Optimization,13.060557,170.578154,10.500793,0.186568,50.728954,0.420877
2,LGBM Regressor with Successive Halving,13.025979,169.676119,10.471541,0.186077,50.090149,0.423940
3,LGBM Regressor CMA-ES,13.012765,169.332064,10.455792,0.185682,48.579596,0.425108